"""Tests for audio codec compatibility filter (Bug 2 fix).

All ffprobe calls use real binaries and real video files generated by the
real_video / two_aac_videos / mixed_codec_videos fixtures in conftest.py.
No subprocess patching.
"""
import logging
import subprocess
from pathlib import Path

import pytest

from combine import filter_compatible_videos, get_video_audio_codec


class TestGetVideoAudioCodec:

    def test_returns_aac_for_aac_video(self, real_video):
        codec = get_video_audio_codec(real_video)
        assert codec == "aac"

    def test_returns_none_for_nonexistent_file(self, tmp_path):
        codec = get_video_audio_codec(tmp_path / "does_not_exist.mp4")
        assert codec is None

    def test_returns_none_for_empty_file(self, tmp_path):
        bad = tmp_path / "empty.mp4"
        bad.write_bytes(b"")
        codec = get_video_audio_codec(bad)
        assert codec is None

    def test_returns_none_for_corrupt_file(self, tmp_path):
        corrupt = tmp_path / "corrupt.mp4"
        corrupt.write_bytes(b"\x00" * 100)
        codec = get_video_audio_codec(corrupt)
        assert codec is None

    def test_mp3_audio_detected(self, tmp_path):
        """A video encoded with libmp3lame has audio codec 'mp3'."""
        mp3_video = tmp_path / "mp3_video.mp4"
        subprocess.run(
            [
                "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                "-f", "lavfi", "-i", "testsrc=duration=3:size=320x240:rate=30",
                "-f", "lavfi", "-i", "sine=frequency=440:duration=3",
                "-c:v", "libx264", "-c:a", "libmp3lame",
                str(mp3_video),
            ],
            check=True,
        )
        codec = get_video_audio_codec(mp3_video)
        assert codec == "mp3"


class TestFilterCompatibleVideos:

    def test_empty_dict_returns_empty(self):
        assert filter_compatible_videos({}) == {}

    def test_single_video_always_passes(self, real_video):
        result = filter_compatible_videos({"only": real_video})
        assert set(result.keys()) == {"only"}

    def test_all_same_codec_all_kept(self, two_aac_videos):
        result = filter_compatible_videos(two_aac_videos)
        assert set(result.keys()) == {"id_a", "id_b"}

    def test_minority_codec_dropped(self, mixed_codec_videos):
        # Two AAC + one MP3 → MP3 dropped
        result = filter_compatible_videos(mixed_codec_videos)
        assert "id_aac1" in result
        assert "id_aac2" in result
        assert "id_mp3" not in result

    def test_minority_codec_logs_warning(self, mixed_codec_videos, caplog):
        with caplog.at_level(logging.WARNING, logger="combine"):
            filter_compatible_videos(mixed_codec_videos)
        assert any("incompatible" in r.message.lower() for r in caplog.records)

    def test_unknown_codec_file_kept(self, tmp_path, real_video):
        """Files where ffprobe can't determine codec are kept (can't confirm incompatible)."""
        bad = tmp_path / "unreadable.mp4"
        bad.write_bytes(b"\x00" * 50)
        result = filter_compatible_videos({"good": real_video, "bad": bad})
        assert "good" in result
        assert "bad" in result

    def test_preserves_insertion_order(self, two_aac_videos):
        result = filter_compatible_videos(two_aac_videos)
        assert list(result.keys()) == list(two_aac_videos.keys())

    def test_custom_logger_receives_warning(self, mixed_codec_videos):
        import logging
        records = []

        class _Capture(logging.Handler):
            def emit(self, record):
                records.append(record)

        log = logging.getLogger("test_custom")
        log.addHandler(_Capture())
        log.setLevel(logging.WARNING)
        filter_compatible_videos(mixed_codec_videos, logger=log)
        assert any("incompatible" in r.getMessage().lower() for r in records)

    def test_all_unknown_codecs_all_kept(self, tmp_path):
        """If ffprobe fails on every file, all are kept."""
        bad1 = tmp_path / "bad1.mp4"
        bad2 = tmp_path / "bad2.mp4"
        bad1.write_bytes(b"\x00" * 50)
        bad2.write_bytes(b"\x00" * 50)
        result = filter_compatible_videos({"a": bad1, "b": bad2})
        assert set(result.keys()) == {"a", "b"}
